### PR TITLE
Added missing file that broke the run

### PR DESCRIPTION
**Pull request by genebean**

### CODE REVIEW

**Comment by mwrock** [comment]
Thanks!

**Comment by genebean** [comment]
Glad to help!

**Comment by genebean** [comment]
@mwrock - after getting past this error I ran into #27 and am stuck again if you happen to have time to take a look. Thanks!

**Comment by mwrock** [comment]
so I dont think I ever ran on win7 with guest additions. I think that got added after I created a win7 image. Overall I found that creating win7images is very much optimized for the extremely patient and pain loving type. It took nearly 24 hours to run if I recall correctly. Another thing I found is that it would fail at the end unless I ran the build "headless".

**Comment by genebean** [comment]
Alright then... guess I'll keep plugging away. Thanks.

**Pull request merged**
